### ISSUE TITLE
Release knip-tess4j 1.1.0

### ISSUE THREAD

**Issue by Squareys** [knime-ip/knip-tess4j#7]
With #6 finally merged, knip-tess4j should be finally ready for a new release.

The `1.1.0` release will feature:
 - Enhanced node configuration dialog and added option to turn off deskew to save performance
 - Parallel Execution of Tess4J Nodes is now possible
 - Now using Tesseract vesion 3.0.4
 - Fixed bug in example workflow (and #5 "Invalid Memory Access on Windows") and removed the thresholder which caused bad results.

The changes can be found on the `develop` branch. Plugin, Fragments, Feature and Update Site versions have been increased already.

**Comment by dietzc** [comment]
can you file a PR? I will review, merge and release afterwards. Thanks for your efforts!

**Comment by Squareys** [comment]
To master? Sure.

**Comment by Squareys** [comment]
See #8
