### ISSUE TITLE
Invalid Memory Access (Windows 10 - 64 bit)

### ISSUE THREAD

**Issue by Squareys** [knime-ip/knip-tess4j#9]
From KNIME forum post: https://tech.knime.org/forum/knime-image-processing/tess4j-node-execute-failed-invalid-memory-access

**Comment by Squareys** [comment]
I will be working on this s.the rest of this day.

**Comment by Squareys** [comment]
So far: Tess4J Node can't deal with the ImageView image type output by the "Segment Cropper", so it seems. Will see what I can do about that.

**Comment by dietzc** [comment]
Maybe because of non zero minimum?

**Comment by Squareys** [comment]
It seems rather random (like a C null pointer somewhere), it doesn't actually seem to be connected to the ImgView.

**Comment by Squareys** [comment]
The node only seems to fail on 32-bit images (implication, not equivalence)

**Comment by Squareys** [comment]
Alright, simple, but hard to explain:

One of the Tess4J functions converted the input image to grey:
```
if (!(buff instanceof DataBufferByte)) {
    bi = ImageHelper.convertImageToGrayscale(bi);
    buff = bi.getRaster().getDataBuffer();
}
```
Problem with this is that it can change the size of a pixel (from 32 to 8 for example). We pass the pixel size of the unconverted input image to tesseract, though:
```
setImage(image.getWidth(),
         image.getHeight(),
		 ImageIOHelper.convertImageData(image), // <- possible data conversion here
		 rect,
		 image.getColorModel().getPixelSize()); // <- pixel size of original data
```
This causes tesseract to have incorrect information about the image buffer size, cause it to read "out of bounds" (32 bits per pixel, instead of 8 bits per pixel, amount of pixels number of times), which in C is not a problem until you reach data which does not belong to you anymore. In some cases you will never reach that point, which is why the node randomly didn't fail, but you just read garbage.
